apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresdb-config
  namespace: casopractico2
  labels:
    app: postgresbd
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgredb-pv-volume
  namespace: casopractico2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgredb-pv-claim
  namespace: casopractico2
spec:
  storageClassName: managed-premium
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb
  namespace: casopractico2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
        - name: postgresdb
          image: postgresdb:casopractico2
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgresdb-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgredb-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgresdb
  namespace: casopractico2
  labels:
    app: postgresdb
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: postgresdb
